version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    container_name: jupyter_notebook
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
  jupyter22:
    build: 
      context: .
      dockerfile: ./docker/LEHCUSTOM/Dockerfile
    ports:
      - 2222:22
    container_name: LEHCUSTOM
