name: Deploy Docker Compose

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  deploy:
    runs-on: OMNIVERSE  # Specify your self-hosted runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy Docker Compose
      run: |
        docker-compose -f $GITHUB_WORKSPACE/docker-compose.yml up -d
